set schema RECIPES;

DROP CONSTANT IF EXISTS UNIQUE_RECIPE_INGREDIENT;
DROP INDEX IF EXISTS UNIQUE_INGREDIENT;
DROP INDEX IF EXISTS UNIQUE_RECIPE;

DROP TABLE IF EXISTS RECIPE_INGREDIENT;
DROP TABLE IF EXISTS INGREDIENT;
DROP TABLE IF EXISTS RECIPE;

CREATE TABLE RECIPE (
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name varchar(128) NOT NULL,
    description clob,
    instructions clob,
    photo blob
);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_RECIPE ON RECIPE(name);

CREATE TABLE INGREDIENT (
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name varchar(64) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQUE_INGREDIENT ON INGREDIENT(name);

CREATE TABLE RECIPE_INGREDIENT (
    id int PRIMARY KEY NOT NULL AUTO_INCREMENT,
    recipe_id int NOT NULL,
    ingredient_id int NOT NULL,
    unit varchar(20) DEFAULT NULL,
    amount decimal(4,2) DEFAULT NULL,
    foreign key (recipe_id) references RECIPE(id),
    foreign key (ingredient_id) references INGREDIENT(id)
);

ALTER TABLE RECIPE_INGREDIENT ADD CONSTRAINT UNIQUE_RECIPE_INGREDIENT UNIQUE(recipe_id, ingredient_id);
